version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: ["--replSet", "rs0", "--bind_ip_all"]
  
  cerebro-service:
    build:
      context: ./services/cerebro_service
    container_name: cerebro-service
    volumes:
      - ./services:/app/services
      - /home/omid/Desktop/keys:/credentials:ro
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/pubsub.json
      - GCP_PROJECT_ID=mathematricks-trader-480718
      - ACCOUNT_DATA_SERVICE_URL=http://account-data-service:8082
    depends_on:
      - mongodb

  execution-service:
    build:
      context: ./services/execution_service
    container_name: execution-service
    volumes:
      - ./services:/app/services
      - /home/omid/Desktop/keys:/credentials:ro
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/pubsub.json
      - GCP_PROJECT_ID=mathematricks-trader-480718
      - ACCOUNT_DATA_SERVICE_URL=http://account-data-service:8082
    depends_on:
      - account-data-service
      - mongodb
      

  signal-ingestion:
    build:
      context: ./services/signal_ingestion
    container_name: signal-ingestion
    volumes:
      - ./services:/app/services
      - /home/omid/Desktop/keys:/credentials:ro
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/pubsub.json
      - GCP_PROJECT_ID=mathematricks-trader-480718
    depends_on:
      - mongodb

  account-data-service:
    build:
      context: ./services/account_data_service                  
    container_name: account-data-service
    ports:
      - "8082:8082"
    volumes:
      - ./services:/app/services
    environment:      
      - MONGODB_URI=mongodb://mongodb:27017/?replicaSet=rs0
    depends_on:
      - mongodb

  frontend:
    build: ./frontend-admin
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  mongo_data:
